<?xml version="1.0"?>
<package format="2">
  <name>forest_loop_detector</name>
  <version>0.1.0</version>
  <description>Forest-LIO-Loop: Triangle descriptor based loop closure detection for FAST-LIO2 in forest environments</description>

  <maintainer email="humbleor@example.com">humbleor</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>message_filters</depend>

  <build_depend>cmake_modules</build_depend>

</package>
